#!/bin/sh

# Deluge Build Tool (DBT)
# Build script for DelugeFirmware, blatantly borrowed from 'fbt' used by
# flipperdevices/flipperzero-firmware and licensed under GNU GPL

# shellcheck disable=SC2086 source=/dev/null
# unofficial strict mode
set -eu;

# private variables
N_GIT_THREADS="$(getconf _NPROCESSORS_ONLN)";
SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)";
SCONS_DEFAULT_FLAGS="--warn=target-not-built";
SCONS_EP="python3 -m SCons";

# public variables
POETRY_ACTIVE="${POETRY_ACTIVE:-""}";
DBT_NOENV="${DBT_NOENV:-""}";
DBT_NO_SYNC="${DBT_NO_SYNC:-""}";
DBT_TOOLCHAIN_PATH="${DBT_TOOLCHAIN_PATH:-$SCRIPT_PATH}";
DBT_VERBOSE="${DBT_VERBOSE:-""}";
SCONS_RUNNER="${SCONS_RUNNER:-""}";

if [ -z "$POETRY_ACTIVE" ]; then
    SCONS_RUNNER="poetry run ";
fi

if [ -z "$DBT_NOENV" ]; then
    DBT_VERBOSE="$DBT_VERBOSE" . "$SCRIPT_PATH/scripts/toolchain/dbtenv.sh";
fi

if [ -z "$DBT_VERBOSE" ]; then
    SCONS_DEFAULT_FLAGS="$SCONS_DEFAULT_FLAGS -Q";
fi

if [ -z "$DBT_NO_SYNC" ]; then
    if [ ! -d "$SCRIPT_PATH/.git" ]; then
        echo "\".git\" directory not found, please clone repo via \"git clone\"";
        exit 1;
    fi
    git submodule update --init --depth 1 --jobs "$N_GIT_THREADS";
fi

$SCONS_RUNNER$SCONS_EP $SCONS_DEFAULT_FLAGS "$@"