//! Host-only invariant harness for the resource manager — the model the proptest
//! and (future) cargo-fuzz target drive, analogous to `deluge_alloc::testing`.
//! Exercises acquire/release/touch/reference churn against a real heap + manager
//! and checks the core invariants after every op:
//!   - every leased pointer is unique (no two live leases alias),
//!   - a leased chunk's bytes stay its materialize pattern (never evicted/corrupted),
//!   - acquire/release never panics or returns a misaligned pointer.

extern crate std;
use crate::{
    deluge_resource_acquire, deluge_resource_create, deluge_resource_define_asset,
    deluge_resource_reference, deluge_resource_release, deluge_resource_touch, BACKING_HEAP,
    COST_IO,
};
use core::ffi::c_void;
use std::vec::Vec;

const NUM_ASSETS: u32 = 4;
const CHUNKS_PER_ASSET: u32 = 8;
const CHUNK_SIZE: usize = 16 * 1024;

fn owner(a: u32) -> *mut c_void {
    (a as usize + 1) as *mut c_void
}
fn pattern(a: u32, index: u32) -> u8 {
    (a as u8)
        .wrapping_mul(31)
        .wrapping_add(index as u8)
        .wrapping_add(0x5A)
}

unsafe extern "C" fn materialize(
    _ctx: *mut c_void,
    owner: *mut c_void,
    index: u32,
    dest: *mut u8,
    len: usize,
) -> bool {
    let a = (owner as usize - 1) as u32;
    core::ptr::write_bytes(dest, pattern(a, index), len);
    true
}

/// One op in a churn sequence (decoded from fuzzer bytes or generated by proptest).
#[derive(Clone, Copy, Debug)]
pub enum Op {
    Acquire { asset: u32, index: u32 },
    Release { which: usize },
    Touch { which: usize },
    Reference { asset: u32 },
}

struct Lease {
    ptr: *mut u8,
    asset: u32,
    index: u32,
}

pub struct Harness {
    mgr: *mut crate::DelugeResource,
    assets: Vec<u32>,
    live: Vec<Lease>,
    _buf: Vec<u128>,
}

impl Harness {
    pub fn new(heap_bytes: usize, chunk_cap: usize) -> Self {
        // 16-aligned arena (Vec<u128>) — see the note in lib.rs's `heap` helper.
        let words = heap_bytes.div_ceil(16);
        let mut buf = std::vec![0u128; words];
        let h =
            unsafe { deluge_alloc::deluge_heap_create(buf.as_mut_ptr() as *mut u8, words * 16) };
        let mgr = unsafe { deluge_resource_create(h, NUM_ASSETS as usize + 1, chunk_cap) };
        assert!(!mgr.is_null());
        let assets = (0..NUM_ASSETS)
            .map(|a| unsafe {
                deluge_resource_define_asset(
                    mgr,
                    owner(a),
                    Some(materialize),
                    None,
                    core::ptr::null_mut(),
                    COST_IO,
                    BACKING_HEAP,
                )
            })
            .collect();
        Harness {
            mgr,
            assets,
            live: Vec::new(),
            _buf: buf,
        }
    }

    pub fn step(&mut self, op: Op) {
        match op {
            Op::Acquire { asset, index } => {
                let asset = self.assets[(asset % NUM_ASSETS) as usize];
                let index = index % CHUNKS_PER_ASSET;
                let p = unsafe { deluge_resource_acquire(self.mgr, asset, index, CHUNK_SIZE) };
                if !p.is_null() {
                    assert_eq!(p as usize % 16, 0, "misaligned acquire");
                    self.live.push(Lease {
                        ptr: p,
                        asset,
                        index,
                    });
                }
            }
            Op::Release { which } => {
                if !self.live.is_empty() {
                    let l = self.live.remove(which % self.live.len());
                    unsafe { deluge_resource_release(self.mgr, l.ptr) };
                }
            }
            Op::Touch { which } => {
                if !self.live.is_empty() {
                    let l = &self.live[which % self.live.len()];
                    unsafe { deluge_resource_touch(self.mgr, l.ptr) };
                }
            }
            Op::Reference { asset } => {
                let asset = self.assets[(asset % NUM_ASSETS) as usize];
                unsafe { deluge_resource_reference(self.mgr, asset) };
            }
        }
        self.check();
    }

    /// Invariants over the currently-leased chunks: each keeps its materialize
    /// pattern (a leased chunk is never evicted or corrupted).
    fn check(&self) {
        for (i, l) in self.live.iter().enumerate() {
            let logical = self.assets.iter().position(|&x| x == l.asset).unwrap() as u32;
            let want = pattern(logical, l.index);
            for k in (0..CHUNK_SIZE).step_by(1024) {
                assert_eq!(
                    unsafe { *l.ptr.add(k) },
                    want,
                    "lease {i} corrupted at byte {k}"
                );
            }
        }
    }
}

/// Decode fuzzer bytes into a churn sequence and run it (the cargo-fuzz entry).
pub fn run_bytes(data: &[u8]) {
    let mut h = Harness::new(256 * 1024, 64);
    let mut it = data.chunks_exact(3);
    for c in it.by_ref() {
        let op = match c[0] % 4 {
            0 => Op::Acquire {
                asset: c[1] as u32,
                index: c[2] as u32,
            },
            1 => Op::Release {
                which: c[1] as usize,
            },
            2 => Op::Touch {
                which: c[1] as usize,
            },
            _ => Op::Reference { asset: c[1] as u32 },
        };
        h.step(op);
    }
}
