#!/usr/bin/env python3

# clang-tidy review - post comments
# Copyright (c) 2022 Peter Hill
# SPDX-License-Identifier: MIT
# See LICENSE for more information

import argparse
import pathlib
import pprint
import sys

from clang_tidy_review import (
    REVIEW_FILE,
    PullRequest,
    add_auth_arguments,
    bool_argument,
    download_artifacts,
    get_auth_from_arguments,
    load_and_merge_reviews,
    load_metadata,
    post_annotations,
    post_review,
    strip_enclosing_quotes,
)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Post a review based on feedback generated by the clang-tidy-review action"
    )

    parser.add_argument("--repo", help="Repo name in form 'owner/repo'")
    parser.add_argument(
        "--max-comments",
        help="Maximum number of comments to post at once",
        type=int,
        default=25,
    )
    parser.add_argument(
        "--lgtm-comment-body",
        help="Message to post on PR if no issues are found. An empty string will post no LGTM comment.",
        type=str,
        default='clang-tidy review says "All clean, LGTM! :+1:"',
    )
    parser.add_argument(
        "--dry-run", help="Run and generate review, but don't post", action="store_true"
    )
    parser.add_argument(
        "--workflow_id",
        help="ID of the workflow that generated the review",
        default=None,
    )
    parser.add_argument(
        "--annotations",
        help="Use annotations instead of comments",
        type=bool_argument,
        default=False,
    )
    parser.add_argument(
        "--num-comments-as-exitcode",
        help="Set the exit code to be the amount of comments",
        type=bool_argument,
        default=True,
    )
    add_auth_arguments(parser)
    parser.add_argument(
        "reviews",
        metavar="REVIEW_FILES",
        type=pathlib.Path,
        nargs="*",
        default=[pathlib.Path(REVIEW_FILE)],
        help="Split workflow review results",
    )

    args = parser.parse_args()

    pull_request = PullRequest(args.repo, None, get_auth_from_arguments(args))

    # Try to read the review artifacts if they're already present
    metadata = load_metadata()
    review = load_and_merge_reviews(args.reviews)

    # If not, try to download them automatically
    if metadata is None and args.workflow_id is not None:
        print("Attempting to automatically download review artifacts", flush=True)
        metadata, review = download_artifacts(pull_request, int(args.workflow_id))

    if metadata is None:
        raise RuntimeError("Couldn't find review metadata")

    pull_request.pr_number = metadata["pr_number"]

    print(
        "clang-tidy-review generated the following review",
        pprint.pformat(review, width=130),
        flush=True,
    )

    if args.annotations:
        exit_code = post_annotations(pull_request, review)
    else:
        lgtm_comment_body = strip_enclosing_quotes(args.lgtm_comment_body)
        exit_code = post_review(
            pull_request, review, args.max_comments, lgtm_comment_body, args.dry_run
        )

    return (exit_code or 0) if args.num_comments_as_exitcode else 0


if __name__ == "__main__":
    sys.exit(main())
