# See https://prettier.io/docs/ci
name: autofix.ci
on:
  pull_request:
    paths:
      - "website/**"
  push:
    paths:
      - "website/**"
permissions: {}
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 10.24.0
          run_install: false
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: website/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Format website
        run: pnpm run check:fix
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
