name: Nightly Build

on:
  workflow_dispatch: # allows manual triggering
# To enable scheduled nightly builds, uncomment the schedule below:
#  schedule:
#    - cron: "14 0 * * *" # runs daily at 00:14

jobs:
  nightly-detect:
    runs-on: ubuntu-latest
    outputs:
      new-commits: ${{ steps.count-commits.outputs.count }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Get new commits if branch exists
        id: count-commits
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/next; then
            echo "Branch next exists, checking for commits"
            git checkout next
            count=$(git log --oneline --since '24 hours ago' | wc -l)
            echo "Saw $count commits"
            echo "count=$count" >> $GITHUB_OUTPUT
          else
            echo "Branch next does not exist, skipping"
            echo "count=0" >> $GITHUB_OUTPUT
          fi
  nightly-build:
    uses: ./.github/workflows/build.yml
    needs: nightly-detect
    if: needs.nightly-detect.outputs.new-commits > 0
    with:
      firmware-retention-days: 30
      build-type: "Release"
      build-tag: "nightly"
      branch: "next"
  nightly-publish:
    uses: ./.github/workflows/publish.yml
    needs: nightly-build
    with:
      tag: "nightly"
      branch: "next"
