name: Build and Check Website

on:
  pull_request:
    paths:
      - "website/**"
  workflow_dispatch:

permissions:
  checks: write
  contents: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 10.24.0
          run_install: false
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Playwright is needed for rendering mermaid diagrams at build time
      # See: https://github.com/remcohaszing/rehype-mermaid?tab=readme-ov-file#installation
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium chromium-headless-shell

      # This gets us the site base URL
      - name: Setup Pages
        id: setup_pages
        uses: actions/configure-pages@v6

      - name: Run website checks
        run: pnpm run check

      - name: Build website
        run: pnpm run build
        env:
          SITE_URL: ${{ steps.setup_pages.outputs.base_url }}
          SITE_BASE_PATH: ${{ steps.setup_pages.outputs.base_path }}

      # We upload the artifact for manual downloading and opening locally
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: website-artifact
          path: website/dist
